"""empty message

Revision ID: 415504688216
Revises: e28541149a66
Create Date: 2017-11-01 16:31:07.583957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415504688216'
down_revision = 'e28541149a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
